# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :buildSimple do |options|

  	# cocoapods
	# git_pull
  	configuration = options[:configuration] ? options[:configuration] : 'Debug'

  	# 更新版本号
  	increment_build_number_in_plist(xcodeproj: 'Beside.xcodeproj', scheme: 'Beside', build_configuration_name: configuration)

    # disable_automatic_code_signing(path: "Beside.xcodeproj")
  	# build
  	gym(scheme: 'Beside', 
  		configuration: configuration, 
  		export_method: 'development',
  		output_directory: '../build',
  		include_bitcode: false)
  	# enable_automatic_code_signing(path: "Beside.xcodeproj")
  end

  lane :beta do
    increment_build_number
    # 开发证书
    
    build_app
  end

  lane :deploy do
  	# 执行 pod install
  	cocoapods

  	# 增加build版本号
  	increment_build_number

  	# 编译代码
  	gym

  end
end
